#!/bin/sh
module="ccp"
device="ccpkp"
mode="664"


# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || ((dmesg | tail) && exit 1)

# only need the following for char-dev
if [ "$1" = "ipc=1" ];
then

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# retrieve major number
major=$(awk "\$2==\"$device\" {print \$1; exit}" /proc/devices)

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/${device}
mknod /dev/${device} c $major 0
chgrp $group /dev/${device}
chmod $mode  /dev/${device}

fi
